
server:  
  port: ${PORT:8081}

spring.application.name: microservice-perfil
eureka:
  client:
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    metadata-map:
      instanceId:  ${spring.application.name}:${random.uuid}

spring:
  boot:
      admin:
        client:
          enabled: true
          url: http://localhost:8090/
         
  datasource:
    driver-class-name: org.postgresql.Driver
    username: adminrs
    password: adminrs
    url: jdbc:postgresql://localhost:5432/bd_perfiles

  jpa:
    hibernate:
      ddlAuto: validate
      #namingStrategy: org.hibernate.cfg.EJB3NamingStrategy
    show-sql: true
    
  flyway:
    enabled: true
    locations: classpath:db/migration/
    user: adminrs
    password: adminrs
